CREATE TABLE tasks
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    status      VARCHAR(255),
    priority    VARCHAR(255),
    created     TIMESTAMP WITHOUT TIME ZONE,
    finished    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);