CREATE TABLE tasks
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    status      SMALLINT,
    priority    SMALLINT,
    created     TIMESTAMP WITHOUT TIME ZONE,
    updated     TIMESTAMP WITHOUT TIME ZONE,
    finished    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tb_tasks PRIMARY KEY (id)
);