CREATE TABLE status_history
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_id INTEGER                                  NOT NULL,
    status  SMALLINT,
    updated TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_status_history PRIMARY KEY (id)
);